# Composer PHP Dependency Manager Configuration
# Defines available composer commands

tools:
  - name: composer_install
    enabled: true
    description: |
      Install dependencies from composer.lock file.

      Always run in the Drupal project directory (/var/www/html).
      Installs packages with versions locked in composer.lock.

    type: command
    command_template: "composer install {args}"
    ssh_target: "web"
    ssh_user: "${DDEV_SSH_USER}"
    working_dir: "/var/www/html"
    default_args:
      args: "--no-interaction"

    input_schema:
      type: object
      properties:
        args:
          type: string
          description: Additional flags (e.g., "--no-dev")

  - name: composer_update
    enabled: true
    description: |
      Update dependencies to latest versions.

      Always run in the Drupal project directory (/var/www/html).
      Updates packages according to version constraints in composer.json.

    type: command
    command_template: "composer update {package} {args}"
    ssh_target: "web"
    ssh_user: "${DDEV_SSH_USER}"
    working_dir: "/var/www/html"
    default_args:
      args: "--no-interaction"

    input_schema:
      type: object
      properties:
        package:
          type: string
          description: Package to update (optional, leave empty for all)
        args:
          type: string
          description: Additional flags

  - name: composer_require
    enabled: true
    description: |
      Add a new dependency to composer.json.

      Always run in the Drupal project directory (/var/www/html).
      Adds a package and updates composer.lock.

      Troubleshooting installation failures:

      1. **PHP Version Incompatibility** - Package may require different PHP version
         - Check PHP version: Use drush_php_eval "echo PHP_VERSION;"
         - Check composer.json: Look for "platform" sections with PHP constraints
         - Try: composer require drupal/package --ignore-platform-req=php-ext-*

      2. **Stability Constraints** - Package below minimum-stability threshold
         - Try: composer require drupal/package:@dev (or @beta, @alpha)
         - Or update composer.json "minimum-stability" to "dev"

      3. **Memory Errors** - Large installation can exceed PHP memory limit
         - Try: COMPOSER_MEMORY_LIMIT=-1 composer require drupal/package

      4. **Dependency Conflicts** - New package conflicts with existing ones
         - Try: composer require drupal/package --with-all-dependencies
         - This updates related packages to compatible versions

    type: command
    command_template: "composer require {package} {args}"
    ssh_target: "web"
    ssh_user: "${DDEV_SSH_USER}"
    working_dir: "/var/www/html"
    default_args:
      args: "--no-interaction"

    input_schema:
      type: object
      properties:
        package:
          type: string
          description: Package to require (e.g., drupal/pathauto)
        args:
          type: string
          description: Additional flags
      required:
        - package