# Agents container compose file
# Managed by VS Code DevContainer, connects to DDEV network
name: ${COMPOSE_PROJECT_NAME}
services:
  agents:
    container_name: ddev-${DDEV_PROJECT}-agents
    # CHANGE THIS LINE: Use the Python 3 image (supports Apple Silicon)
    image: mcr.microsoft.com/devcontainers/python:3-bookworm
    hostname: agents
    restart: "no"
    entrypoint: ["/bin/bash"]
    command:
      - "-c"
      - |
        exec sudo -u vscode bash -c "cd /workspace && exec sleep infinity"
    volumes:
      - ../:/workspace:cached
      - ddev-global-cache:/mnt/ddev-global-cache
    working_dir: /workspace
    environment:
      - DDEV_PROJECT=${DDEV_PROJECT}
    networks:
      - default
    labels:
      com.ddev.site-name: ${DDEV_PROJECT}
      com.ddev.app-type: agents

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
    external: true

volumes:
  ddev-global-cache:
    external: true
